---
{{- $host := (pluck .Values.env .Values.app.url | first | default .Values.app.url._default) }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}
  annotations:
    nginx.ingress.kubernetes.io/whitelist-source-range: {{ join "," (pluck .Values.werf.env .Values.app.whitelist | first | default .Values.app.whitelist._default ) }}
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: {{ (pluck .Values.env .Values.app.cors | first | default .Values.app.cors._default) | quote }}
spec:
  ingressClassName: {{ pluck .Values.env .Values.app.ingressClass | first | default .Values.app.ingressClass._default }}
  rules:
  - host: {{ $host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Chart.Name }}
            port:
              name: http
 # tls:
 #   - hosts:
 #     - {{ $host }}
 #     secretName: {{ pluck .Values.werf.env .Values.app.tlsSecretName | first | default .Values.app.tlsSecretName._default }}
