app:
  hpa:
    enabled:
      _default: true
    replicas:
      min:
        _default: 1
      max:
        _default: 3
    averageValue: #cpu
      _default: 80
  ingressClass:
    _default: nginx
  url:
    dev:
    production:
  tlsSecretName:
    _default:
    production:
  whitelist:
    _default:
      - "0.0.0.0/0"

resources:
  app:
    _default:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        memory: 128Mi
