name: Terraform Init

on:
 workflow_dispatch:

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ inputs.tf-version }}
        terraform_wrapper: ${{ inputs.terraform-wrapper }}
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      if: ${{ inputs.local-execution-mode == 'true' }}
      with:
        role-to-assume: ${{ inputs.terraform-execution-iam-role-arn }}
        role-session-name: terraform-execution-role
        aws-region: ${{ inputs.aws-region }}
        role-duration-seconds: 1200
    - name: Setup Python
      uses: actions/setup-python@v4
      if: ${{ inputs.setup-python == 'true' }}
      with:
        python-version: ${{ inputs.python-version }}
    - name: Terraform Init
      id: init
      shell: bash
      run: terraform init
